server:
  # insecure: true
  # service:
  #   type: LoadBalancer
  #   ports:
  #     http: 8080
  #     https: 8443
  service:
    type: LoadBalancer
    servicePortHttp: 8080
    servicePortHttps: 8443

configs:
  params:
    server.insecure: true

crds:
  keep: false
